### ISSUE TITLE
put请求 参数后台接收不到

### ISSUE THREAD

**Issue by huangping35** [JohnnyHooo/HJNetwork#10]
[HJNetwork.m:301行] 
请求参数 = {
  "uid" : "2d989ba09d57488cb6c82d8f03dc8eec",
  "cardNo" : "12345678901",
  "cardPwd" : "1"
}
请求方式 = PUT
缓存策略 = 只从网络获取数据，且数据不会缓存在本地
版本缓存 = 未启用
[HJNetwork.m:365行] 请求结果 = {
  "msg" : "Missing required arguments:userId",
  "data" : null,
  "code" : 3
}

发送put请求后，后台接收不到参数，其他的get，post都可以，请大佬，尽快解决。
用afn直接发put请求就可以。

//    AFHTTPSessionManager *m=[AFHTTPSessionManager manager];
//    [m PUT:[baseUrl stringByAppendingString:URL] parameters:parameters success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
//        NSLog(@"resp %@",responseObject);
//    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
//        NSLog(@"error %@",error);
//    }];

直接调用afnetworking的put就可以了，你封装的put,传参到后台，后台接收不到参数，请大佬尽快解决，一直支持大佬。

**Comment by huangping35** [comment]
用afnetworking的put请求就可以。

**Comment by huangping35** [comment]
用的版本是1.2.4，应该是最新的吧，发送put，后台接收不到参数。

**Comment by JohnnyHooo** [comment]
我看好像是你们后台报错了，提示“ msg”：“缺少必需的参数：userId”，

**Comment by JohnnyHooo** [comment]
是不是参数的key传错了？

**Comment by huangping35** [comment]
不是 参数根本没有传到后台

**Comment by huangping35** [comment]
大佬 可以测试一下 你用你的hjnetwork 然后再用afn 分别调用 put 请求 ，就会发现hjnetwork没有传参数到后台  afn就传参数到后台了

**Comment by huangping35** [comment]
大佬 我上次反映说put请求没有响应 你修复后put请求的响应 参数忘记了传到后台或者为nil了？

**Comment by huangping35** [comment]
> 我看好像是你们后台报错了，提示“ msg”：“缺少必需的参数：userId”，

大佬，我检查了代码，用你封装的hjnetwork，后台的确收不到参数，直接调用afnetworking的put，后台就可以收到参数。我记得上次说put请求没有任何响应，大佬就修复了，我看了一下好像是因为设为nil，这是会不会也是参数设为nil了？

**Comment by huangping35** [comment]
> 是不是参数的key传错了？

key没有错，反复测试过了，参数真的没有传到后台，后面就直接调用afnetworking的put才行。

**Comment by huangping35** [comment]
大佬，我在github上面也搜索了类似你的网络架构，例如msnetwork，这个也是put请求不行，与你类似，看着他的写法，与你类似。

**Comment by huangping35** [comment]
定位到原因啦，是后台的原因。五该晒大佬。

**Comment by JohnnyHooo** [comment]
😂这都半个月了，你们才定位到问题啊。。。
