### ISSUE TITLE
put 没有任何反应

### ISSUE THREAD

**Issue by huangping35** [JohnnyHooo/HJNetwork#7]
[HJNetwork.m:301行]
请求参数 = {
"code" : "123456",
"mobile_code_id" : "37"
}
请求URL = http://hui.fighter.ltd/front/phone/18688874035
请求方式 = PUT
缓存策略 = 只从网络获取数据，且数据不会缓存在本地
版本缓存 = 未启用
调用你封装的put没有任何响应，但是直接调用afnetworking的put就可以了，不知道是什么原因？

**Comment by JohnnyHooo** [comment]
已定位到问题.目前已修复!

**Comment by JohnnyHooo** [comment]
修复版本号是 1.2.4

**Comment by huangping35** [comment]
@JohnnyHooo ok，测试没有问题了，谢谢大佬。
